language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t cpittman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cpittman/docker-react npm run test